export const messages = {
  es: {
    project_name_op: '1️⃣  Ponele nombre a tu proyecto:',
    project_empty_name: '⚠️ El nombre no puede estar vacío',
    cancel_op: '🫢  Cancelaste la operación.',
    template_op: '2️⃣  Seleccioná el template de Vite:',
    pckg_mng_op: '3️⃣  Seleccioná el manejador de paquetes:',
    install_pckgs_op: '🪄  ¿Instalamos los paquetes?',
    optional_tools_op: '💡 ¿Agregamos otras herramientas?',
    eslint_config_op: '🤔 ¿Que tipo de configuración queres para ESLint?',
    prettier_config_op: '🤔 ¿Que tipo de configuración queres para Prettier?',
    config_eslint_sp: '⏳  Configurando ESLint...',
    config_eslint_ok: '✅  ESLint configurado!',
    config_prettier_sp: '⏳ Configurando Prettier...',
    config_prettier_ok: '✅  Prettier configurado!',
    config_lintstg_sp: '⏳  Configurando Lint Staged...',
    config_lintstg_ok: '✅  Lint Staged configurado!',
    config_husky_sp: '⏳  Configurando Husky',
    config_husky_ok: '✅  Husky configurado!',
    intalling_pckgs_sp:
      '⏳  Instalando paquetes via _manager_... puede tardar unos segundos!',
    intalling_pckgs_ok: '✅  Instalación finalizada',
    installing_err: '🚨  Error instalando dependencias: _stderr_',
    exist_dir: '🥴  El directorio _name_ ya existe, elegí otro nombre.',
    saving_changes_pjson: '⏳  Guardando cambios en package.json',
    saved_changes_pjson: '✅  Cambios guardados en package.json',
    read_file_err: '🚨  Error leyendo el archivo _path_: _msg',
    deleted_folder: '🗑️  El directorio _name_ se borró con exito.',
    vite_creating_sp: '⏳ Ejecutando la creación del proyecto: _directory_ ',
    vite_creating_ok: '✅ Proyecto _directory_ creado exitosamente',
    vite_err: '🚨  Error creando el template de Vite: _stderr_',
    welcome: 'Hola 🤗 vamo a crear tu nuevo proyecto Vite personalizado!...',
    finish: '🥳 Tu proyecto está listo para usar! Seguí estos pasos',
    thanks:
      'Apoya el proyecto dejándole una ⭐️ al repo https://github.com/vamoacodear/create-custom-vite gracias 💜 _vamoacodear_',
  },
  en: {
    project_name_op: '1️⃣  Name your project:',
    project_empty_name: '⚠️ The name cannot be empty.',
    cancel_op: '🫢  You canceled the operation.',
    template_op: '2️⃣  Select Vite template:',
    pckg_mng_op: '3️⃣  Select package manager:',
    install_pckgs_op: '🪄  Shall we install the packages?',
    optional_tools_op: '💡 Shall we add other tools?',
    eslint_config_op: '🤔 What kind of configuration do you want for ESLint?',
    prettier_config_op:
      '🤔 What kind of configuration do you want for Prettier?',
    config_eslint_sp: '⏳  Configuring ESLint...',
    config_eslint_ok: '✅  ESLint configured!',
    config_prettier_sp: '⏳ Configuring Prettier...',
    config_prettier_ok: '✅  Prettier configured!',
    config_lintstg_sp: '⏳  Configuring Lint Staged...',
    config_lintstg_ok: '✅  Lint Staged configured!',
    config_husky_sp: '⏳  Configuring Husky!',
    config_husky_ok: '✅  Husky configured!',
    intalling_pckgs_sp:
      '⏳  Installing packages via _manager_... may take a few seconds!',
    intalling_pckgs_ok: '✅  Installation completed!',
    installing_err: '🚨  Error installing dependencies: _stderr_',
    exist_dir: '🥴  The _name_ directory already exists, I chose another name.',
    saving_changes_pjson: '⏳  Saving changes to package.json',
    saved_changes_pjson: '✅  Changes saved to package.json',
    read_file_err: '🚨  Error reading _path_ file: _msg',
    deleted_folder: '🗑️ _name_ folder was deleted successfully.',
    vite_creating_sp: '⏳ Running project creation: _directory_ ',
    vite_creating_ok: '✅ _directory_ project created successfully',
    vite_err: '🚨  Error creating Vite template: _stderr_',
    welcome: "Hello 🤗 let's create your new custom Vite project!...",
    finish: '🥳 Your project is ready to use! Follow these steps',
    thanks:
      'Support the project by leaving a ⭐️ to the repo https: //github.com/vamoacodear/create-custom-vite thank you 💜 _vamoacodear_',
  },
}
